logo: 光轴 # top-left logo in index page

more: # more links at top right index page
  # links: /links.html
  Github: https://github.com/hhongwen/
  # rss: /rss2.xml

footer_info: © hhw 2018-2020 # about info at right foot
about: # about link at right foot
  title: be yourserf
  link: https://github.com/hhongwen/

excerpt_num: 120

# 是否渲染 文章目录
toc: true

# 是否支持 数学公式
mathjax: true

# 是否开启 音乐组件
player: true

latex: true

# If you want to use valine,you should get the appId and appKey form https://leancloud.cn ,more setting please see https://valine.js.org
valine:
  enable: false # !!if you want use valine comment system,please set enable: true
  appId: #your leancloud appId
  appKey: #your leancloud appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  avatar: mm # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: false # valine verify code (true/false)
  notify: false # valine mail notify (true/false)
  lang: zh-cn

bookmark:
  -
    nickname: 笔记 # 昵称
    site: https://note.hhongwen.work # 站点地址
